### ISSUE TITLE
Solution incomplete. Please share InstagramApiSharpMine (replica of InstagramApiSharp)

### ISSUE THREAD

**Issue by mediaexplorer74** [NGame1/Winsta11#16]
Hi. I downloaded your last dev-version of Winsta11 and detected that InstagramApiSharp.UWP project not found.
If InstagramApiSharpMine is special replica of InstagramApiSharp, please share it (or include into your Winsta11 solution).

Cheers up,
MediaExplorer

**Comment by NGame1** [comment]
Hi there, That's a paid version of Instagram API Sharp library written by @ramtinak 
I don't have any permission to share that in public.

**Comment by mediaexplorer74** [comment]
> NGame1

Hi, [NGame1](https://github.com/NGame1).
Ok, I understand you. Thanks for reply.
Well, I simply deleted Winsta11 ) Game over.

**Comment by NGame1** [comment]
It's compatible with Windows 10 Mobile. Currently, there are some test versions also for Windows 10 Mobile on our insiders' group. 
https://t.me/WinstaInsiders
If you mean something that I misunderstood please let me know.
