### ISSUE TITLE
zip file missing project?

### ISSUE THREAD

**Issue by ancich** [NGame1/Winsta11#20]
So I download the zip file for the, but when I open it up in Visual Studio, one of the projects "InstagramApiSharp.UWP" shows up as "not found".

**Comment by NGame1** [comment]
For those who wanna build this project, Please ping me on WigoTag group on Telegram, I will send them the InstagramApiSharp.UWP dll to be able to build the project.
WingoTag Telegram Group: https://t.me/WinstaInsiders
Thank you.

**Comment by ancich** [comment]
I thought the point of a GitHub repo is to be.... you know... a repo.

**Comment by NGame1** [comment]
I can't provide a paid library here. As I'm not the owner. 
Also, many other projects have missing parts like Unigram that you need TDLib or etc. 
When you are not the owner and the libraries linked are not owned by the project author, we can not share them publicly.

**Comment by ancich** [comment]
I see.
